# database
database.driver=org.postgresql.Drivers
database.jdbc_url=jdbc:postgresql://localhost:5432/ecommerce
database.username=postgres
database.password=123456
database.max_pool_size=10

#hibernate
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true